insert into phone_type (name) values ('mobil');
insert into phone_type (name) values ('festnetz');
insert into phone_type (name) values ('office');
insert into person (nachname, vorname) values ('Doe', 'John');
insert into person (nachname, vorname) values ('Doe', 'Jane');
insert into person (nachname, vorname) values ('Mustermann', 'Max');
insert into person (nachname, vorname) values ('Musterfrau', 'Maxima');
insert into address (city, country, street, zip_code) values ('Erfurt', 'Deutschland', 'Urbicher Weg 29', '99099');
insert into address (city, country, street, zip_code) values ('Dresden', 'Deutschland', 'Zeisig Gasse 34', '09874');
insert into address (city, country, street, zip_code) values ('Chemnitz', 'Deutschland', 'Holunder Allee 22b', '08974');
insert into phone_number (number, phone_type_id) values ('+49-1512-123456',1);
insert into phone_number (number, phone_type_id) values ('+49-(0) 3451-123456',2);
insert into phone_number (number, phone_type_id) values ('+49-(0) 345-123-0',3);
insert into phone_number (number, phone_type_id) values ('+49-(0) 3532-433-1',3);
insert into phone_number (number, phone_type_id) values ('+49-(0) 1742-433-1',1);
insert into address_phone_number_list (address_id, phone_number_list_id) values (1,2);
insert into address_phone_number_list (address_id, phone_number_list_id) values (2,3);
insert into address_phone_number_list (address_id, phone_number_list_id) values (3,4);
insert into person_address_list (person_id, address_list_id) values (1,1);
insert into person_address_list (person_id, address_list_id) values (2,1);
insert into person_address_list (person_id, address_list_id) values (2,2);
insert into person_address_list (person_id, address_list_id) values (3,2);
insert into person_address_list (person_id, address_list_id) values (4,2);
insert into person_address_list (person_id, address_list_id) values (4,3);
insert into person_phone_number_list (person_id, phone_number_list_id) values (1,1);
insert into person_phone_number_list (person_id, phone_number_list_id) values (2,1);
insert into person_phone_number_list (person_id, phone_number_list_id) values (4,5);